/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as ApprovalsRouteImport } from './routes/approvals'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BackupsRouteImport } from './routes/backups'
import { Route as CallsRouteImport } from './routes/calls'
import { Route as ContentRouteImport } from './routes/content'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DataOverviewRouteImport } from './routes/data-overview'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as FeatureflagsRouteImport } from './routes/featureflags'
import { Route as GroupsRouteImport } from './routes/groups'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as OverviewRouteImport } from './routes/overview'
import { Route as PostsRouteImport } from './routes/posts'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SecurityCenterRouteImport } from './routes/security-center'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SystemRouteImport } from './routes/system'
import { Route as UsersRouteImport } from './routes/users'

const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const ApprovalsRoute = ApprovalsRouteImport.update({
  id: '/approvals',
  path: '/approvals',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupsRoute = BackupsRouteImport.update({
  id: '/backups',
  path: '/backups',
  getParentRoute: () => rootRouteImport,
} as any)
const CallsRoute = CallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentRoute = ContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DataOverviewRoute = DataOverviewRouteImport.update({
  id: '/data-overview',
  path: '/data-overview',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const FeatureflagsRoute = FeatureflagsRouteImport.update({
  id: '/featureflags',
  path: '/featureflags',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupsRoute = GroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewRoute = OverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRouteImport,
} as any)
const PostsRoute = PostsRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityCenterRoute = SecurityCenterRouteImport.update({
  id: '/security-center',
  path: '/security-center',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutRoute
  '/analytics': typeof AnalyticsRoute
  '/announcements': typeof AnnouncementsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/backups': typeof BackupsRoute
  '/calls': typeof CallsRoute
  '/content': typeof ContentRoute
  '/dashboard': typeof DashboardRoute
  '/data-overview': typeof DataOverviewRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/featureflags': typeof FeatureflagsRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/moderation': typeof ModerationRoute
  '/overview': typeof OverviewRoute
  '/posts': typeof PostsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/security': typeof SecurityRoute
  '/security-center': typeof SecurityCenterRoute
  '/settings': typeof SettingsRoute
  '/system': typeof SystemRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutRoute
  '/analytics': typeof AnalyticsRoute
  '/announcements': typeof AnnouncementsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/backups': typeof BackupsRoute
  '/calls': typeof CallsRoute
  '/content': typeof ContentRoute
  '/dashboard': typeof DashboardRoute
  '/data-overview': typeof DataOverviewRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/featureflags': typeof FeatureflagsRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/moderation': typeof ModerationRoute
  '/overview': typeof OverviewRoute
  '/posts': typeof PostsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/security': typeof SecurityRoute
  '/security-center': typeof SecurityCenterRoute
  '/settings': typeof SettingsRoute
  '/system': typeof SystemRoute
  '/users': typeof UsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRoute
  '/analytics': typeof AnalyticsRoute
  '/announcements': typeof AnnouncementsRoute
  '/approvals': typeof ApprovalsRoute
  '/audit': typeof AuditRoute
  '/backups': typeof BackupsRoute
  '/calls': typeof CallsRoute
  '/content': typeof ContentRoute
  '/dashboard': typeof DashboardRoute
  '/data-overview': typeof DataOverviewRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/featureflags': typeof FeatureflagsRoute
  '/groups': typeof GroupsRoute
  '/login': typeof LoginRoute
  '/moderation': typeof ModerationRoute
  '/overview': typeof OverviewRoute
  '/posts': typeof PostsRoute
  '/profile': typeof ProfileRoute
  '/reports': typeof ReportsRoute
  '/security': typeof SecurityRoute
  '/security-center': typeof SecurityCenterRoute
  '/settings': typeof SettingsRoute
  '/system': typeof SystemRoute
  '/users': typeof UsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/announcements'
    | '/approvals'
    | '/audit'
    | '/backups'
    | '/calls'
    | '/content'
    | '/dashboard'
    | '/data-overview'
    | '/diagnostics'
    | '/featureflags'
    | '/groups'
    | '/login'
    | '/moderation'
    | '/overview'
    | '/posts'
    | '/profile'
    | '/reports'
    | '/security'
    | '/security-center'
    | '/settings'
    | '/system'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/announcements'
    | '/approvals'
    | '/audit'
    | '/backups'
    | '/calls'
    | '/content'
    | '/dashboard'
    | '/data-overview'
    | '/diagnostics'
    | '/featureflags'
    | '/groups'
    | '/login'
    | '/moderation'
    | '/overview'
    | '/posts'
    | '/profile'
    | '/reports'
    | '/security'
    | '/security-center'
    | '/settings'
    | '/system'
    | '/users'
  id:
    | '__root__'
    | '/_layout'
    | '/analytics'
    | '/announcements'
    | '/approvals'
    | '/audit'
    | '/backups'
    | '/calls'
    | '/content'
    | '/dashboard'
    | '/data-overview'
    | '/diagnostics'
    | '/featureflags'
    | '/groups'
    | '/login'
    | '/moderation'
    | '/overview'
    | '/posts'
    | '/profile'
    | '/reports'
    | '/security'
    | '/security-center'
    | '/settings'
    | '/system'
    | '/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AnnouncementsRoute: typeof AnnouncementsRoute
  ApprovalsRoute: typeof ApprovalsRoute
  AuditRoute: typeof AuditRoute
  BackupsRoute: typeof BackupsRoute
  CallsRoute: typeof CallsRoute
  ContentRoute: typeof ContentRoute
  DashboardRoute: typeof DashboardRoute
  DataOverviewRoute: typeof DataOverviewRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  FeatureflagsRoute: typeof FeatureflagsRoute
  GroupsRoute: typeof GroupsRoute
  LoginRoute: typeof LoginRoute
  ModerationRoute: typeof ModerationRoute
  OverviewRoute: typeof OverviewRoute
  PostsRoute: typeof PostsRoute
  ProfileRoute: typeof ProfileRoute
  ReportsRoute: typeof ReportsRoute
  SecurityRoute: typeof SecurityRoute
  SecurityCenterRoute: typeof SecurityCenterRoute
  SettingsRoute: typeof SettingsRoute
  SystemRoute: typeof SystemRoute
  UsersRoute: typeof UsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/approvals': {
      id: '/approvals'
      path: '/approvals'
      fullPath: '/approvals'
      preLoaderRoute: typeof ApprovalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backups': {
      id: '/backups'
      path: '/backups'
      fullPath: '/backups'
      preLoaderRoute: typeof BackupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calls': {
      id: '/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof CallsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/content': {
      id: '/content'
      path: '/content'
      fullPath: '/content'
      preLoaderRoute: typeof ContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data-overview': {
      id: '/data-overview'
      path: '/data-overview'
      fullPath: '/data-overview'
      preLoaderRoute: typeof DataOverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/featureflags': {
      id: '/featureflags'
      path: '/featureflags'
      fullPath: '/featureflags'
      preLoaderRoute: typeof FeatureflagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/groups': {
      id: '/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof GroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/posts': {
      id: '/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof PostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security-center': {
      id: '/security-center'
      path: '/security-center'
      fullPath: '/security-center'
      preLoaderRoute: typeof SecurityCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRoute,
  AnalyticsRoute: AnalyticsRoute,
  AnnouncementsRoute: AnnouncementsRoute,
  ApprovalsRoute: ApprovalsRoute,
  AuditRoute: AuditRoute,
  BackupsRoute: BackupsRoute,
  CallsRoute: CallsRoute,
  ContentRoute: ContentRoute,
  DashboardRoute: DashboardRoute,
  DataOverviewRoute: DataOverviewRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  FeatureflagsRoute: FeatureflagsRoute,
  GroupsRoute: GroupsRoute,
  LoginRoute: LoginRoute,
  ModerationRoute: ModerationRoute,
  OverviewRoute: OverviewRoute,
  PostsRoute: PostsRoute,
  ProfileRoute: ProfileRoute,
  ReportsRoute: ReportsRoute,
  SecurityRoute: SecurityRoute,
  SecurityCenterRoute: SecurityCenterRoute,
  SettingsRoute: SettingsRoute,
  SystemRoute: SystemRoute,
  UsersRoute: UsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
