-- ══════════════════════════════════════════════════════════════════
-- V22: محاذاة المخطط مع كيانات JPA — أول اجتياز لفحص Hibernate validate في التاريخ
-- اكتُشفت بمطابقة ساكنة شاملة لكل الكيانات الـ23 مع DDL الترحيلات.
-- إضافي بالكامل: لا يلمس أي ملف مُطبَّق، ولا يحتاج مسحاً للأحجام.
-- ══════════════════════════════════════════════════════════════════

-- ━━━━ 1) مفاتيح بديلة لكيانات @Id ذات التوليد IDENTITY ━━━━
-- الجداول أُنشئت بمفاتيح مركبة فقط، بينما الكيانان EventAttendee/HashtagFollow
-- يتطلبان عمود id من نوع Long بتوليد هوية. المفاتيح المركبة تبقى كما هي.
ALTER TABLE event_attendees ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE hashtag_follows  ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;

-- ━━━━ 2) محاذاة الكسور العائمة: الكيانات Double ↔ double precision ━━━━
-- v_trending_hashtags تعتمد على trending_score وPostgreSQL يمنع تغيير نوع عمود
-- تعتمد عليه عروض → نسقط العرض مؤقتاً ونعيد إنشاءه بعد التحويل.
DROP VIEW IF EXISTS v_trending_hashtags;
ALTER TABLE events    ALTER COLUMN location_lat   TYPE DOUBLE PRECISION USING location_lat::double precision;
ALTER TABLE events    ALTER COLUMN location_lng   TYPE DOUBLE PRECISION USING location_lng::double precision;
ALTER TABLE hashtags  ALTER COLUMN trending_score TYPE DOUBLE PRECISION USING trending_score::double precision;
CREATE OR REPLACE VIEW v_trending_hashtags AS
SELECT
    id, tag_name, usage_count, posts_count, trending_score,
    is_trending, last_used_at
FROM hashtags
WHERE is_blocked = FALSE
ORDER BY trending_score DESC, usage_count DESC
LIMIT 100;

-- ━━━━ 3) حقول JSONB/INET/ARRAY مقابل String في الكيانات → TEXT ━━━━
-- الكيانات تربط هذه الحقول كنصوص عادية (String?)؛ validate في Hibernate 6 يطابق
-- النوع (jsonb/inet/array تُسجَّل Types#OTHER فيرفضها) — والتطبيق لا يستخدم
-- أي معاملات JSONB/ARRAY عليها، فالتحويل إلى TEXT شفاف تماماً.
ALTER TABLE admin_audit_log       ALTER COLUMN metadata        TYPE TEXT USING metadata::text;
ALTER TABLE admin_sessions        ALTER COLUMN device_info     TYPE TEXT USING device_info::text;

-- ip_address: `host()` يقبل inet فقط. على قاعدة سبق أن حُوِّل فيها العمود إلى
-- varchar (أو أُنشئ نصيًا من الأصل) كان هذا السطر يرفع
-- `function host(character varying) does not exist` فيُسقط الترحيل بالكامل —
-- وهو ما جمّد السلسلة عند V22. الآن يُقرأ النوع الفعلي أولاً: التحويل يجري
-- بـ host() على inet وحده، ويُتجاهل إن كان العمود نصيًا بالفعل.
DO $$
DECLARE
    t record;
BEGIN
    FOR t IN
        SELECT table_name
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name IN ('admin_audit_log', 'admin_sessions')
          AND column_name = 'ip_address'
          AND udt_name = 'inet'
    LOOP
        EXECUTE format(
            'ALTER TABLE %I ALTER COLUMN ip_address TYPE TEXT USING host(ip_address)',
            t.table_name
        );
    END LOOP;
END $$;
ALTER TABLE feature_flags         ALTER COLUMN config          TYPE TEXT USING config::text;
ALTER TABLE feature_flags         ALTER COLUMN target_user_ids TYPE TEXT USING target_user_ids::text;
ALTER TABLE feature_flags         ALTER COLUMN target_groups   TYPE TEXT USING target_groups::text;
ALTER TABLE system_announcements  ALTER COLUMN target_user_ids TYPE TEXT USING target_user_ids::text;
ALTER TABLE system_health         ALTER COLUMN details         TYPE TEXT USING details::text;
ALTER TABLE user_reports          ALTER COLUMN evidence        TYPE TEXT USING evidence::text;
