#!/usr/bin/env python3
"""Build a fresh-install Flyway B64 snapshot without rewriting historical V*.sql.

The historical upgrade chain includes broken, previously published PSTN-era
migrations. Editing those files changes checksums for installations which have
already recorded them. Flyway's B64 migration runs ONLY on a new empty database;
existing databases with schema history ignore it. This generator is deliberately
strict: if a historic source is changed, patch assertions must be reviewed.

This is a transitional, un-compacted baseline: after applying the versioned
schema in memory it removes the retired PSTN tables via V52 and the remaining
legacy tables via V53–V55. No data from an existing installation is copied.
"""
from __future__ import annotations

import sys
from pathlib import Path

from list_flyway_migrations import ordered_migrations

ROOT = Path(__file__).resolve().parent.parent
MIGRATIONS = ROOT / "RED_Ultimate_V1-main/RED_Ultimate/backend-server/src/main/resources/db/migration"
BASELINE = MIGRATIONS / "B64__Sovereign_Fresh_Install.sql"


def replace_once(sql: str, original: str, correction: str, version: str) -> str:
    count = sql.count(original)
    if count != 1:
        raise ValueError(f"{version}: expected one instance of {original!r}; found {count}")
    return sql.replace(original, correction)


def correct_for_new_install(version: str, sql: str) -> str:
    # V26_1 creates dinstar_cdr for the first time, not V15 as its later
    # comments claimed. Its views, V40 and V44 disagree with the old SERIAL
    # definition. This table is DROPPED by V52, but must exist long enough for
    # earlier versions' references to compile on a fresh database.
    if version == "V26_1__Dinstar_Enhanced.sql":
        sql = replace_once(sql,
            "CREATE TABLE IF NOT EXISTS dinstar_cdr (\n    id SERIAL PRIMARY KEY,",
            "CREATE TABLE IF NOT EXISTS dinstar_cdr (\n    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),", version)
        sql = replace_once(sql, "    duration INTEGER, -- بالثواني",
            "    duration INTEGER,\n    duration_seconds INTEGER,\n"
            "    ring_duration_seconds INTEGER NOT NULL DEFAULT 0,\n"
            "    status VARCHAR(20), -- legacy reports through V52", version)
    elif version == "V28_1__Admin_RBAC_and_Security_Hardening.sql":
        sql = replace_once(sql, "    (gen_random_uuid(), 'SUPPORT', 'USER_VIEW'),\nON CONFLICT",
            "    (gen_random_uuid(), 'SUPPORT', 'USER_VIEW')\nON CONFLICT", version)
    elif version == "V46__Yemen_Mobile_Cellular_Multi_Operator.sql":
        # pstn_tariffs is NOT created by any committed migration. Its old
        # UPDATE/INSERT cannot run on a new database and tariffs are retired.
        # Retain the rest of V46 so V52 can remove the obsolete schema.
        anchor = "-- ── 2. radio_type"
        if sql.count(anchor) != 1 or "UPDATE pstn_tariffs" not in sql:
            raise ValueError(f"{version}: tariff removal needs review")
        sql = "-- V46 fresh baseline: skip tariff writes (table was never created).\n" + sql[sql.index(anchor):]
    elif version == "V58__Retention_Indexes_And_Orphan_Guards.sql":
        # V53 dropped both tables; V59 contains the definitive retention fix.
        for stale in (
            "CREATE INDEX IF NOT EXISTS idx_message_delivery_receipts_msg ON message_delivery_receipts(message_uuid);\n",
            "CREATE INDEX IF NOT EXISTS idx_sent_prekeys_consumed ON sent_prekey_records(consumed_at) WHERE consumed_at IS NOT NULL;\n",
        ):
            sql = replace_once(sql, stale, "", version)
        sql = replace_once(sql,
            "idx_backup_history_created ON backup_history(created_at DESC)",
            "idx_backup_history_created ON backup_history(started_at DESC)", version)
    return sql


def render() -> str:
    ordered = ordered_migrations(MIGRATIONS)
    if ordered[-1].name != "V64__Schema_Reconciliation_And_Missing_Tables.sql":
        raise ValueError("A newer version exists; use a NEW B-version after reviewing the schema")
    # V62/63 assumed that V64's columns/tables already existed. On a new DB,
    # run their analytics and indexes only after V64 establishes that schema.
    deferred = {"V62__Channel_Analytics_Materialized_Views.sql", "V63__Live_Stream_Indexes.sql"}
    regular = [path for path in ordered if path.name not in deferred]
    extra = [path for path in ordered if path.name in deferred]
    ordered = regular + extra
    header = (
        "-- Flyway B64: a FRESH empty database only. Existing schema histories ignore B64.\n"
        "-- Generated by scripts/generate-flyway-baseline.py; DO NOT HAND-EDIT.\n"
        "-- Historical V*.sql remain unchanged to preserve applied checksums.\n"
        "-- Legacy PSTN objects are dropped by the included V52/V53/V54/V55 steps.\n"
        "-- This is NOT an upgrade or repair script for an existing database.\n\n"
    )
    pieces = [header]
    for path in ordered:
        sql = correct_for_new_install(path.name, path.read_text(encoding="utf-8-sig"))
        # Historical SQL can contain trailing spaces; the generated file must
        # pass whitespace checks without touching its original migration.
        sql = "\n".join(line.rstrip() for line in sql.rstrip().split("\n"))
        pieces.append(f"\n-- ===== Snapshot of {path.name} (fresh install only) =====\n{sql}\n")
    return "".join(pieces)


def main() -> None:
    result = render()
    size = len(result.encode("utf-8"))
    if len(sys.argv) == 2 and sys.argv[1] == "--check":
        if not BASELINE.exists() or BASELINE.read_text(encoding="utf-8") != result:
            raise SystemExit("B64 baseline is stale; re-run scripts/generate-flyway-baseline.py")
        print(f"PASS: deterministic fresh-install B64 baseline ({size} bytes)")
    elif len(sys.argv) == 1:
        BASELINE.write_text(result, encoding="utf-8")
        print(f"Generated {BASELINE.relative_to(ROOT)} ({size} bytes)")
    else:
        raise SystemExit("Usage: generate-flyway-baseline.py [--check]")


if __name__ == "__main__":
    main()
