#!/bin/bash
# RED Sovereign — Kamailio SBC Docker Entrypoint
# Generates kamailio.cfg from environment variables
# Supports: SIP trunking (carriers), remote workers (registrations), topology hiding

set -eu

: "${KAMAILIO_PUBLIC_IP:?KAMAILIO_PUBLIC_IP is required}"
: "${KAMAILIO_PRIVATE_IP:?KAMAILIO_PRIVATE_IP is required}"
: "${ASTERISK_PRIVATE_IP:?ASTERISK_PRIVATE_IP is required}"
: "${DINSTAR_IPS:?DINSTAR_IPS is required}"
: "${KAMAILIO_SIP_DOMAIN:?KAMAILIO_SIP_DOMAIN is required}"

CONFIG_DIR="/etc/kamailio"
mkdir -p "$CONFIG_DIR"

# Parse DINSTAR_IPS into array for carrier matching
IFS=',' read -ra DINSTAR_ARRAY <<< "$DINSTAR_IPS"
DINSTAR_SUBNET=""
for ip in "${DINSTAR_ARRAY[@]}"; do
    DINSTAR_SUBNET="${DINSTAR_SUBNET} $(echo "$ip" | sed 's/\.[0-9]*$/.0\/24/')"
done

cat > "$CONFIG_DIR/kamailio.cfg" <<EOF
#!KAMAILIO
# RED Sovereign — Kamailio SBC Configuration
# Generated by docker-entrypoint.sh on container start
# Architecture: Public Edge → Kamailio (B2BUA) → Private Asterisk + Dindar

#### Global Parameters ####
debug=3
log_stderror=yes
memdbg=5
memlog=5
fork=yes
children=8
disable_tcp=no
disable_tls=no
enable_tls=yes
tcp_connection_lifetime=3605
tcp_max_connections=2048

listen=udp:${KAMAILIO_PRIVATE_IP}:5060
listen=tcp:${KAMAILIO_PRIVATE_IP}:5060
listen=tls:${KAMAILIO_PRIVATE_IP}:5061
listen=udp:${KAMAILIO_PUBLIC_IP}:5060 advertise ${KAMAILIO_PUBLIC_IP}:5060
listen=tcp:${KAMAILIO_PUBLIC_IP}:5060 advertise ${KAMAILIO_PUBLIC_IP}:5060
listen=tls:${KAMAILIO_PUBLIC_IP}:5061 advertise ${KAMAILIO_PUBLIC_IP}:5061

#### Module Loading ####
loadmodule "mi_fifo.so"
loadmodule "kex.so"
loadmodule "corex.so"
loadmodule "tm.so"
loadmodule "sl.so"
loadmodule "rr.so"
loadmodule "maxfwd.so"
loadmodule "usrloc.so"
loadmodule "registrar.so"
loadmodule "textops.so"
loadmodule "textopsx.so"
loadmodule "siputils.so"
loadmodule "xlog.so"
loadmodule "sanity.so"
loadmodule "ctl.so"
loadmodule "cfg_rpc.so"
loadmodule "mi_rpc.so"
loadmodule "acc.so"
loadmodule "dialog.so"
loadmodule "pike.so"
loadmodule "htable.so"
loadmodule "rtpengine.so"
loadmodule "nathelper.so"
loadmodule "sipcapture.so"
loadmodule "topoh.so"
loadmodule "websocket.so"
loadmodule "tls.so"
loadmodule "crypto.so"
loadmodule "auth.so"
loadmodule "auth_db.so"
loadmodule "permissions.so"
loadmodule "drouting.so"
loadmodule "carrierroute.so"
loadmodule "dispatcher.so"

#### Module Parameters ####
modparam("mi_fifo", "fifo_name", "/run/kamailio/kamailio_fifo")
modparam("tm", "fr_timer", 30000)
modparam("tm", "fr_inv_timer", 120000)
modparam("rr", "enable_full_lr", 1)
modparam("rr", "append_fromtag", 1)
modparam("usrloc", "db_mode", 0)
modparam("registrar", "method_filtering", 1)
modparam("sanity", "autodrop", 1)
modparam("pike", "sampling_time_unit", 2)
modparam("pike", "reqs_density_per_unit", 16)
modparam("pike", "remove_latency", 4)
modparam("htable", "htable_size", 1024)
modparam("dialog", "dlg_flag", 4)
modparam("dialog", "timeout_avp", "$avp(i:dialog-timeout)")
modparam("dialog", "default_timeout", 1800)
modparam("acc", "early_media", 1)
modparam("acc", "report_ack", 1)
modparam("acc", "report_cancels", 1)
modparam("acc", "detect_direction", 1)
modparam("acc", "failed_transaction_flag", 6)
modparam("rtpengine", "rtpengine_port", 2223)
modparam("rtpengine", "rtpengine_allow_op", 1)
modparam("rtpengine", "queried_nodes_limit", 4)
modparam("nathelper", "natping_interval", 30)
modparam("nathelper", "ping_nated_only", 1)
modparam("nathelper", "sipping_from", "sip:pinger@${KAMAILIO_SIP_DOMAIN}")
modparam("sipcapture", "server", "udp:127.0.0.1:5060")
modparam("topoh", "mask_key", "REDSOVEREIGN-TOPOH-KEY-CHANGE-IN-PRODUCTION")
modparam("topoh", "mask_ip", "${KAMAILIO_PUBLIC_IP}")
modparam("topoh", "mask_callid", 1)
modparam("websocket", "keepalive_timeout", 30)
modparam("dispatcher", "list_file", "/etc/kamailio/dispatcher.list")
modparam("dispatcher", "flags", 2)
modparam("carrierroute", "carrier_table", "carrier_route")
modparam("carrierroute", "domain_col", "domain")
modparam("carrierroute", "prefix_col", "prefix")
modparam("carrierroute", "suffix_col", "suffix")

#### Routing Logic ####
request_route {
    # 1. Security & Sanity
    if (!sanity_check("1511", "7")) {
        xlog("L_ERR", "Sanity check failed for $rm from $si:$sp\\n");
        sl_send_reply("400", "Bad Request");
        exit;
    }

    # 2. NAT handling for UDP
    if (nat_uac_test("19")) {
        force_rport();
        fix_nated_contact();
    }

    # 3. Handle WebSocket transport
    if ($proto == "WS" || $proto == "WSS") {
        if (is_method("REGISTER")) {
            if (!is_present_hf("Contact")) {
                sl_send_reply("400", "Missing Contact");
                exit;
            }
        }
    }

    # 4. Anti-flood protection (pike)
    if ($rm == "INVITE" && !pike_check_req()) {
        xlog("L_WARN", "Flood detected from $si:$sp - blocking\\n");
        sl_send_reply("429", "Too Many Requests");
        exit;
    }

    # 5. Authentication for registrar (remote workers)
    if (is_method("REGISTER")) {
        if (!is_present_hf("Authorization")) {
            sl_send_reply("401", "Unauthorized");
            www_authorize("${KAMAILIO_SIP_DOMAIN}", "subscriber");
            exit;
        }
        if (!proxy_authorize("${KAMAILIO_SIP_DOMAIN}", "subscriber")) {
            sl_send_reply("403", "Forbidden");
            exit;
        }
        # Forward REGISTER to Asterisk
        $var(asterisk_dst) = "sip:${ASTERISK_PRIVATE_IP}:5060";
        rewritehostport("${ASTERISK_PRIVATE_IP}", "5060");
        route(RELAY);
        exit;
    }

    # 6. Inbound from carriers (Dindar IPs) → Asterisk
    if (is_method("INVITE") && is_from_dindar()) {
        xlog("L_INFO", "Inbound from Dindar $si → Asterisk\\n");
        # Topology hiding: rewrite Via, Contact, Record-Route
        topoh_push();
        # Forward to Asterisk
        rewritehostport("${ASTERISK_PRIVATE_IP}", "5060");
        route(RELAY);
        exit;
    }

    # 7. Outbound from Asterisk → Carriers/Remote
    if (is_from_asterisk()) {
        xlog("L_INFO", "Outbound from Asterisk → Carrier/Remote\\n");
        topoh_push();
        # Carrier routing via carrierroute module
        if (carrierroute_process("outbound")) {
            xlog("L_INFO", "Routed via carrierroute to $ru\\n");
            route(RELAY);
            exit;
        }
        # Fallback: direct to Dindar for PSTN
        if ($ru =~ "sip:.*@${DINSTAR_ARRAY[0]}") {
            rewritehostport("${DINSTAR_ARRAY[0]}", "5060");
            route(RELAY);
            exit;
        }
    }

    # 8. Default deny
    sl_send_reply("403", "Forbidden - No matching route");
    exit;
}

#### Helper Functions ####
function is_from_dindar() {
    # Match source IP against Dindar subnets
    if (${DINSTAR_SUBNET} =~ $si) {
        return 1;
    }
    return 0;
}

function is_from_asterisk() {
    if ($si == "${ASTERISK_PRIVATE_IP}") {
        return 1;
    }
    return 0;
}

#### Relay Route ####
route[RELAY] {
    # Add Record-Route for dialog state
    record_route();
    # RTPengine for media handling
    if (has_body("application/sdp")) {
        rtpengine_offer("ICE=force");
    }
    # Send
    if (!t_relay()) {
        sl_reply_error();
    }
    exit;
}

#### Onreply Route ####
onreply_route {
    # Handle 1xx/2xx responses
    if (t_check_status("1[0-9][0-9]")) {
        if (has_body("application/sdp")) {
            rtpengine_answer("ICE=force");
        }
    }
    if (t_check_status("200")) {
        if (has_body("application/sdp")) {
            rtpengine_answer("ICE=force");
        }
    }
    # Topology hiding on responses
    topoh_pop();
}

#### Failure Route ####
failure_route {
    if (t_check_status("487|408|404|486|603")) {
        xlog("L_INFO", "Call failed/ended: $T_reply_code\\n");
    } else {
        xlog("L_WARN", "Call failure: $T_reply_code - trying next carrier\\n");
        # Carrier failover
        if (carrierroute_next()) {
            topoh_push();
            route(RELAY);
        }
    }
}

#### Branch Route ####
branch_route {
    # Per-branch NAT handling
    if (nat_uac_test("19")) {
        fix_nated_contact();
    }
}

EOF

chown kamailio:kamailio "$CONFIG_DIR/kamailio.cfg" 2>/dev/null || true
echo "[entrypoint] Generated kamailio.cfg"

exec kamailio -f "$CONFIG_DIR/kamailio.cfg" -P /run/kamailio/kamailio.pid -u kamailio -g kamailio -DD -E -e