package com.red.server.social

import org.springframework.data.annotation.Id
import org.springframework.data.mongodb.core.index.Indexed
import org.springframework.data.mongodb.core.mapping.Document
import java.time.Instant

@Document("posts")
data class PostDocument(
    @Id val id: String,
    @Indexed val authorId: String,
    @Indexed val authorRedId: String,
    val authorUsername: String,
    val authorDisplayName: String,
    val text: String,
    @Indexed val visibility: PostVisibility,
    val kind: PostKind = PostKind.POST,
    @Indexed val parentId: String? = null,
    val quotePostId: String? = null,
    val poll: Poll? = null,
    val media: List<PostMedia> = emptyList(),
    val linkCard: LinkCard? = null,
    val voiceMetadata: VoiceMetadata? = null,
    val mentions: List<String> = emptyList(),
    val hashtags: List<String> = emptyList(),
    val disappearingAt: Instant? = null,
    @Indexed val createdAt: Instant = Instant.now(),
    val editedAt: Instant? = null,
    @Indexed val deletedAt: Instant? = null,
    val reactionCounts: Map<String, Long> = emptyMap(),
    val replyCount: Long = 0,
    val repostCount: Long = 0
)

/**
 * خصوصية المنشور. `FRIENDS` أضافها main ويستعملها `FeedService` فعلًا
 * في ترشيح الفيد، ولذلك بقيت.
 */
enum class PostVisibility { PUBLIC, FRIENDS, LOCAL_YEMEN }

/**
 * نطاق الفيد المطلوب.
 *
 * `FRIENDS` حلّ محلّ `FOLLOWING`، و`PUBLIC` حلّ محلّ `YEMEN`.
 * والفرق ليس تسمية فقط: «المتابَعة» علاقة أحادية الاتجاه (أتابعك دون
 * أن تتابعني)، أما «الأصدقاء» فعلاقة متبادلة يلزم فيها أن يكون كلٌّ
 * منّا في جهات اتصال الآخر — وهذا ما يطبّقه `FeedService`.
 *
 * `FOLLOWING` و`YEMEN` مُبقاتان مهجورتين لا تُعرضان في الواجهة: نسخ
 * التطبيق المثبَّتة على الأجهزة ما زالت ترسلهما، وحذفهما يجعل Spring
 * يردّ 400 على كل طلب منها.
 */
enum class FeedScope {
    ALL,
    FRIENDS,
    PUBLIC,

    @Deprecated("استعمل FRIENDS — أُبقيت لتوافق النسخ المثبَّتة", ReplaceWith("FRIENDS"))
    FOLLOWING,

    @Deprecated("استعمل PUBLIC — أُبقيت لتوافق النسخ المثبَّتة", ReplaceWith("PUBLIC"))
    YEMEN;

    /** يوحّد القيم المهجورة إلى ما يقابلها، فيبقى منطق الفيد فرعين لا أربعة. */
    fun canonical(): FeedScope = when (this) {
        FOLLOWING -> FRIENDS
        YEMEN -> PUBLIC
        else -> this
    }
}
enum class PostKind { POST, POLL }
data class PostMedia(
    val objectKey: String,
    val mimeType: String,
    val width: Int? = null,
    val height: Int? = null,
    val durationMs: Long? = null,
    val voiceWaveform: List<Int> = emptyList()
)
data class Poll(val options: List<PollOption>, val expiresAt: Instant?)
data class PollOption(val id: String, val text: String, val votes: Long = 0)

/**
 * LinkCard — Open Graph preview for URLs in posts
 * Generated server-side via LinkCardService
 */
data class LinkCard(
    val url: String,
    val title: String? = null,
    val description: String? = null,
    val imageUrl: String? = null,
    val siteName: String? = null,
    val faviconUrl: String? = null,
    val fetchedAt: Instant = Instant.now()
)

/**
 * VoiceMetadata — extracted from voice messages
 * Generated by MessageService.extractVoiceMetadata()
 */
data class VoiceMetadata(
    val durationMs: Long,
    val waveform: List<Int> = emptyList(),  // 0-100 amplitude samples
    val sampleRateHz: Int = 16000,
    val bitrate: Int = 32000,
    val mimeType: String = "audio/mp4",
    val sizeBytes: Long = 0
)

@Document("post_reactions")
/**
 * تفاعل على منشور. المعرّف مركّب `postId:userId:type` فبحث التبديل
 * الحالي يمرّ على `_id` ولا يمسح المجموعة.
 *
 * ومع ذلك `postId` و`userId` مُفهرسان: أي استعلام مستقبلي بمعنى
 * «كل تفاعلات هذا المنشور» أو «كل ما تفاعل معه هذا المستخدم» —
 * وهو استعلام طبيعي جدًّا لشاشة تفاعلات أو لحذف حساب — سيمسح
 * المجموعة كاملة بلا هذين الفهرسين، ولن يظهر العطب إلا بعد أن
 * تكبر البيانات في الإنتاج.
 */
data class PostReaction(@Id val id: String, @Indexed val postId: String, @Indexed val userId: String, val type: String, val createdAt: Instant = Instant.now())

@Document("poll_votes")
/**
 * صوت في استطلاع. المعرّف `postId:userId` يمنع التصويت مرّتين.
 * الفهارس لاستعلامات النتائج التفصيلية وحذف بيانات المستخدم.
 */
data class PollVote(@Id val id: String, @Indexed val postId: String, @Indexed val userId: String, @Indexed val optionId: String, val createdAt: Instant = Instant.now())

@Document("follows")
data class FollowDocument(
    @Id val id: String,
    @Indexed val followerId: String,
    @Indexed val followedId: String,
    val createdAt: Instant = Instant.now()
)

@Document("hidden_posts")
data class HiddenPost(@Id val id: String, @Indexed val userId: String, @Indexed val postId: String, val createdAt: Instant = Instant.now())

@Document("muted_authors")
data class MutedAuthor(@Id val id: String, @Indexed val userId: String, @Indexed val authorId: String, val createdAt: Instant = Instant.now())

@Document("post_reports")
data class PostReport(@Id val id: String, @Indexed val postId: String, @Indexed val reporterId: String, val reason: String, val status: String = "OPEN", val createdAt: Instant = Instant.now())

data class CreatePostRequest(
    val text: String,
    val visibility: PostVisibility = PostVisibility.PUBLIC,
    val parentId: String? = null,
    val quotePostId: String? = null,
    val pollOptions: List<String> = emptyList(),
    val pollDurationHours: Int? = null,
    val media: List<PostMedia> = emptyList(),
    val linkCard: LinkCard? = null,
    val voiceMetadata: VoiceMetadata? = null,
    /** Mentions extracted from text (@RED_ID) */
    val mentions: List<String> = emptyList(),
    /** Hashtags extracted from text (#tag) */
    val hashtags: List<String> = emptyList(),
    /** Disappearing message duration in seconds (0 = permanent) */
    val disappearingSeconds: Int = 0
)
data class ReactionRequest(val type: String, val active: Boolean)
data class PollVoteRequest(val optionId: String)
data class EditPostRequest(val text: String)
data class HidePostRequest(val reason: String? = null)
data class FeedResponse(val posts: List<PostDocument>, val nextCursor: String?)
