package com.red.server.social

import org.springframework.data.annotation.Id
import org.springframework.data.mongodb.core.index.Indexed
import org.springframework.data.mongodb.core.mapping.Document
import java.time.Instant

@Document("posts")
data class PostDocument(
    @Id val id: String,
    @Indexed val authorId: String,
    @Indexed val authorRedId: String,
    val authorUsername: String,
    val authorDisplayName: String,
    val text: String,
    @Indexed val visibility: PostVisibility,
    val kind: PostKind = PostKind.POST,
    @Indexed val parentId: String? = null,
    val quotePostId: String? = null,
    val poll: Poll? = null,
    val media: List<PostMedia> = emptyList(),
    val linkCard: LinkCard? = null,
    val voiceMetadata: VoiceMetadata? = null,
    val mentions: List<String> = emptyList(),
    val hashtags: List<String> = emptyList(),
    val disappearingAt: Instant? = null,
    @Indexed val createdAt: Instant = Instant.now(),
    val editedAt: Instant? = null,
    @Indexed val deletedAt: Instant? = null,
    val reactionCounts: Map<String, Long> = emptyMap(),
    val replyCount: Long = 0,
    val repostCount: Long = 0
)

enum class PostVisibility { PUBLIC, FRIENDS, LOCAL_YEMEN }
enum class FeedScope { ALL, PUBLIC, FRIENDS, FOLLOWING, YEMEN }
enum class PostKind { POST, POLL }
data class PostMedia(
    val objectKey: String,
    val mimeType: String,
    val width: Int? = null,
    val height: Int? = null,
    val durationMs: Long? = null,
    val voiceWaveform: List<Int> = emptyList()
)
data class Poll(val options: List<PollOption>, val expiresAt: Instant?)
data class PollOption(val id: String, val text: String, val votes: Long = 0)

/**
 * LinkCard — Open Graph preview for URLs in posts
 * Generated server-side via LinkCardService
 */
data class LinkCard(
    val url: String,
    val title: String? = null,
    val description: String? = null,
    val imageUrl: String? = null,
    val siteName: String? = null,
    val faviconUrl: String? = null,
    val fetchedAt: Instant = Instant.now()
)

/**
 * VoiceMetadata — extracted from voice messages
 * Generated by MessageService.extractVoiceMetadata()
 */
data class VoiceMetadata(
    val durationMs: Long,
    val waveform: List<Int> = emptyList(),  // 0-100 amplitude samples
    val sampleRateHz: Int = 16000,
    val bitrate: Int = 32000,
    val mimeType: String = "audio/mp4",
    val sizeBytes: Long = 0
)

@Document("post_reactions")
data class PostReaction(@Id val id: String, val postId: String, val userId: String, val type: String, val createdAt: Instant = Instant.now())

@Document("poll_votes")
data class PollVote(@Id val id: String, val postId: String, val userId: String, val optionId: String, val createdAt: Instant = Instant.now())

@Document("follows")
data class FollowDocument(
    @Id val id: String,
    @Indexed val followerId: String,
    @Indexed val followedId: String,
    val createdAt: Instant = Instant.now()
)

@Document("hidden_posts")
data class HiddenPost(@Id val id: String, @Indexed val userId: String, @Indexed val postId: String, val createdAt: Instant = Instant.now())

@Document("muted_authors")
data class MutedAuthor(@Id val id: String, @Indexed val userId: String, @Indexed val authorId: String, val createdAt: Instant = Instant.now())

@Document("post_reports")
data class PostReport(@Id val id: String, @Indexed val postId: String, @Indexed val reporterId: String, val reason: String, val status: String = "OPEN", val createdAt: Instant = Instant.now())

data class CreatePostRequest(
    val text: String,
    val visibility: PostVisibility = PostVisibility.PUBLIC,
    val parentId: String? = null,
    val quotePostId: String? = null,
    val pollOptions: List<String> = emptyList(),
    val pollDurationHours: Int? = null,
    val media: List<PostMedia> = emptyList(),
    val linkCard: LinkCard? = null,
    val voiceMetadata: VoiceMetadata? = null,
    /** Mentions extracted from text (@RED_ID) */
    val mentions: List<String> = emptyList(),
    /** Hashtags extracted from text (#tag) */
    val hashtags: List<String> = emptyList(),
    /** Disappearing message duration in seconds (0 = permanent) */
    val disappearingSeconds: Int = 0
)
data class ReactionRequest(val type: String, val active: Boolean)
data class PollVoteRequest(val optionId: String)
data class EditPostRequest(val text: String)
data class HidePostRequest(val reason: String? = null)
data class FeedResponse(val posts: List<PostDocument>, val nextCursor: String?)
